# Description

This file loads the processed thomasan sequences, then assigns sigma factors based on the −35 and −10 regions upstream of the TSS codon. These sequence motifs are poorly conserved and differ widely among the promoter different σ factor which recognizes them. Furthermore, the consensus motifs recognized by σ24 and σ38 have not been reported owing to low conservation and/or the limited number of confirmed promoters. The canonical consensus for known –35 and –10 regions and the number interspacing nucleotides are (Lewin, 2008):

σ32 -- 5' -- CCCTTTGAA -- 13-15bp CCCGATNT -- 3'
σ28 -- 5' -- CTAAA -- 15bp GCCGATAA -- 3'
σ70 -- 5' -- TTGACA -- 16-18bp TATAAT -- 3'
σ54 -- 5' -- CTGGNA -- 6bp TTGCA -- 3'

In [1]:
import pandas as pd

In [2]:
thomasan_df = pd.read_csv('../../Data/Functional (Thomasan)/Thomasan_full_sequences.csv')
thomasan_df.head()

,Pos,Strand,Sequence -50 nt upstream + TSS (51nt),LB_0.4_detected,LB_2.0_detected,M63_0.4_detected,LB_0.4_enriched,LB_2.0_enriched,M63_0.4_enriched,LB_0.4_stepHeight,LB_2.0_stepHeight,M63_0.4_stepHeight,LB_0.4_stepFactor,LB_2.0_stepFactor,M63_0.4_stepFactor,LB_0.4_enrichmentFactor,LB_2.0_enrichmentFactor,M63_0.4_enrichmentFactor,Sequence
0,113,+,ATAGCAGCTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATTT...,1.0,1.0,1.0,1.0,1.0,1.0,1.96,10.27,1.80,2.33,6.60,4.00,13.27,11.27,25.41,GATAGCAGCTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATT...
1,122,-,TAATTTTTATCTGTCTGTGCGCTATGCCTATATTGGTTAAAGTATT...,0.0,1.0,1.0,0.0,1.0,1.0,0.00,3.13,1.35,0.00,6.50,3.33,0.00,12.54,2.86,TGTAATTTTTATCTGTCTGTGCGCTATGCCTATATTGGTTAAAGTA...
2,148,+,AATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATAT...,1.0,1.0,1.0,1.0,1.0,1.0,64.53,154.97,831.14,10.90,10.96,16.97,2.62,5.86,2.90,AAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATA...
3,412,+,CATCAGTGGCAAATGCAGAACGTTTTCTGCGTGTTGCCGATATTCT...,0.0,1.0,0.0,0.0,1.0,0.0,0.00,24.14,0.00,0.00,41.00,0.00,0.00,12.49,0.00,ACATCAGTGGCAAATGCAGAACGTTTTCTGCGTGTTGCCGATATTC...
4,1176,-,GCACCAATGAGCGTACCTGGTGCTTGAGGATTTCCGGTATTTTTAA...,1.0,1.0,1.0,1.0,1.0,1.0,3.19,9.78,5.01,100.00,100.00,100.00,2.95,5.27,3.41,TGGCACCAATGAGCGTACCTGGTGCTTGAGGATTTCCGGTATTTTT...

In [6]:
def reverse_complement(seq):
    complement = {'A': 'T', 'C': 'G', 'G': 'C', 'T': 'A'}
    return ''.join(complement[base] for base in seq[::-1])

# Apply function conditionally using .apply with a lambda function
df = pd.DataFrame()
df['Sequence'] = thomasan_df.apply(
    lambda row: reverse_complement(row['Sequence']) if row['Strand'] == '-' else row['Sequence'],
    axis=1
)

df.head()

                                            Sequence
0  GATAGCAGCTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATT...
1  AAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATATAGGC...
2  AAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATA...
3  ACATCAGTGGCAAATGCAGAACGTTTTCTGCGTGTTGCCGATATTC...
4  GCCCAGTTCCAGATCCCTTGCCTGATTAAAAATACCGGAAATCCTC...